services:
  redmine:
    image: redmine:latest
    container_name: redmine-kanban
    ports:
      - "3002:3000"
    environment:
      RAILS_ENV: development
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: password
      REDMINE_SECRET_KEY_BASE: supersecretkey
      SECRET_KEY_BASE: supersecretkey
    volumes:
      - ./plugins:/usr/src/redmine/plugins
      - ./themes:/usr/src/redmine/public/themes
    depends_on:
      - db

  db:
    image: mariadb:10
    container_name: redmine-kanban-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: redmine
      MYSQL_USER: redmine
      MYSQL_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
